name: iskxpress
description: "Your iskcellent campus delivery partner."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.0
  flutter_web_auth_2: ^4.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/demo/stalls/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
